# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bundler-download 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "bundler-download".freeze
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["AndyMaleh".freeze]
  s.date = "2020-09-23"
  s.description = "bundler-download is a Bundler plugin for auto-downloading gem-specified extra files (e.g. large file downloads) on `bundle install` from a `Downloadfile`".freeze
  s.email = "andy.am@gmail.com".freeze
  s.executables = ["bundler-download".freeze]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "bin/bundler-download",
    "bundler-download.gemspec",
    "lib/bundler-download.rb",
    "lib/bundler-download/ext/download.rb",
    "lib/bundler/download.rb",
    "lib/bundler/downloadfile.rb",
    "plugins.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/bundler-download".freeze
  s.licenses = ["MIT".freeze]
  s.post_install_message = "*** bundler-download post install message ***\nSome gems have a Downloadfile! Follow the instructions below to download their files. \nAdd `plugin 'bundler-download'` to Gemfile and run `bundle install` \nor alternatively just run `bundle plugin install bundler-download`. \nAfterwards, run `bundle install` and extra gem files will be downloaded automatically.".freeze
  s.rubygems_version = "3.1.4".freeze
  s.summary = "bundler-download is a Bundler plugin for auto-downloading specified extra files on `bundle install`".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<bundler>.freeze, [">= 2.0.0", "< 3.0.0"])
    s.add_runtime_dependency(%q<download>.freeze, [">= 1.1.0", "< 2.0.0"])
    s.add_runtime_dependency(%q<httparty>.freeze, [">= 0.18.1", "< 2.0.0"])
    s.add_runtime_dependency(%q<os>.freeze, [">= 1.1.1", "< 2.0.0"])
    s.add_runtime_dependency(%q<tty-progressbar>.freeze, [">= 0.17.0", "< 2.0.0"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 2.3.5"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_development_dependency(%q<puts_debuggerer>.freeze, [">= 0"])
    s.add_development_dependency(%q<pessimize>.freeze, [">= 0"])
    s.add_development_dependency(%q<rake-tui>.freeze, [">= 0"])
  else
    s.add_dependency(%q<bundler>.freeze, [">= 2.0.0", "< 3.0.0"])
    s.add_dependency(%q<download>.freeze, [">= 1.1.0", "< 2.0.0"])
    s.add_dependency(%q<httparty>.freeze, [">= 0.18.1", "< 2.0.0"])
    s.add_dependency(%q<os>.freeze, [">= 1.1.1", "< 2.0.0"])
    s.add_dependency(%q<tty-progressbar>.freeze, [">= 0.17.0", "< 2.0.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.3.5"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<puts_debuggerer>.freeze, [">= 0"])
    s.add_dependency(%q<pessimize>.freeze, [">= 0"])
    s.add_dependency(%q<rake-tui>.freeze, [">= 0"])
  end
end

